[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kibble"
version = "0.1.0.dev0"
dependencies = [
  "msl-equipment @ git+https://github.com/MSLNZ/msl-equipment.git",
]

[tool.hatch.metadata]
allow-direct-references = true